# This is the configuration used to check the rubocop source code.

AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes: []

Documentation:
  Enabled: false

EmptyLines:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets
